In [1]:
import tensorflow_datasets as tfds
import cv2
import mediapy
import numpy as np
from bs4 import BeautifulSoup

In [2]:
catalog_names = []
with open('catalog.txt', 'r') as f: html_content = f.read()
soup = BeautifulSoup(html_content, 'html.parser')
catalog_names = []
for a_tag in soup.find_all('a', href=True):
    href = a_tag['href']
    if href.startswith('/datasets/catalog/'): 
        catalog_names.append(href.split('/datasets/catalog/')[1])
print(catalog_names)


['aloha_mobile', 'asu_table_top_converted_externally_to_rlds', 'austin_buds_dataset_converted_externally_to_rlds', 'austin_sailor_dataset_converted_externally_to_rlds', 'austin_sirius_dataset_converted_externally_to_rlds', 'bc_z', 'berkeley_autolab_ur5', 'berkeley_cable_routing', 'berkeley_fanuc_manipulation', 'berkeley_gnm_cory_hall', 'berkeley_gnm_recon', 'berkeley_gnm_sac_son', 'berkeley_mvp_converted_externally_to_rlds', 'berkeley_rpt_converted_externally_to_rlds', 'bridge', 'bridge_data_msr', 'cmu_franka_exploration_dataset_converted_externally_to_rlds', 'cmu_play_fusion', 'cmu_stretch', 'columbia_cairlab_pusht_real', 'dlr_edan_shared_control_converted_externally_to_rlds', 'dlr_sara_grid_clamp_converted_externally_to_rlds', 'dlr_sara_pour_converted_externally_to_rlds', 'dobbe', 'eth_agent_affordances', 'fmb', 'fractal20220817_data', 'iamlab_cmu_pickup_insert_converted_externally_to_rlds', 'imperialcollege_sawyer_wrist_cam', 'io_ai_tech', 'jaco_play', 'kaist_nonprehensile_converted

In [3]:
cat = 'fractal20220817_data'
catalog ='gs://gresearch/robotics/' + cat + '/'
builder = tfds.builder_from_directory(catalog + '0.1.0')
n = builder.info.splits['train'].num_examples
print(n)
t = True
for i in range(n):
    if i % 10000 != 0: continue
    print(i)
    split = 'train[{}:{}]'.format(i, i + 1)
    ds = builder.as_dataset(split=split)
    episode = next(iter(ds))
    steps = list(episode['steps'])
    if t:
        t = False
        print(episode.keys())
    print('steps:', len(steps))
    step = steps[0]
    if 'natural_language_instruction' in step['observation']:
        instruction = step['observation']['natural_language_instruction'].numpy().decode('utf-8')
        print(instruction)
    else:
        print("No natural language instruction found in this step.")
    try:
        images = [cv2.resize(np.array(step['observation']['image']), (256, 256)) for step in steps]
        mediapy.show_video(images, fps=10)
    except: continue
    try:
        hand_images = [cv2.resize(np.array(step['observation']['hand_image']), (128, 128)) for step in steps]
        mediapy.show_video(hand_images, fps=10)
    except: continue

2024-10-15 02:49:15.592059: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-15 02:49:15.645864: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-15 02:49:15.667941: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-15 02:49:21.427225: W external/local_tsl/tsl/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP

87212
0


2024-10-15 02:49:25.262802: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:00:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-10-15 02:49:25.315650: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:00:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-10-15 02:49:25.315937: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:00:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-10-15 02:49:25.319245: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:00:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-10-15 02:49:25.319486: I external/local_xla/xla/stream_executor

dict_keys(['aspects', 'attributes', 'steps'])
steps: 115
pick rxbar chocolate from bottom drawer and place on counter


10000


2024-10-15 02:49:37.885428: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


steps: 32
move green can near redbull can


20000


2024-10-15 02:49:44.438281: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


steps: 25
pick banana from white bowl


30000


2024-10-15 02:49:51.189432: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


steps: 26
pick orange from white bowl


40000


2024-10-15 02:49:58.468226: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


steps: 51
move orange can near green rice chip bag


50000


2024-10-15 02:50:04.455695: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


steps: 36
move orange near green jalapeno chip bag


60000


2024-10-15 02:50:13.832811: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


steps: 41
open top drawer


70000


2024-10-15 02:50:19.848174: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


steps: 53
place blue chip bag into middle drawer


80000


2024-10-15 02:50:26.239499: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


steps: 44
place rxbar blueberry into middle drawer


In [4]:
def explore_data_structure(data, depth=0):
    if isinstance(data, dict):
        for key, value in data.items():
            print("  " * depth + f"Key: {key}, Type: {type(value)}")
            explore_data_structure(value, depth + 1)
    elif isinstance(data, list):
        for index, item in enumerate(data):
            print("  " * depth + f"Index: {index}, Type: {type(item)}")
            explore_data_structure(item, depth + 1)
    else:
        print("  " * depth + f"Value: {data}")
# explore_data_structure(episodse)

step = steps[0]
print(step.keys())
for key, value in step.items():
    print(key, type(value))
    if isinstance(value, dict):
        for k, v in value.items():
            print('  ', k, type(v))
    elif isinstance(value, list):
        for i, v in enumerate(value):
            print('  ', i, type(v))
            

dict_keys(['action', 'is_first', 'is_last', 'is_terminal', 'observation', 'reward'])
action <class 'dict'>
   base_displacement_vector <class 'tensorflow.python.framework.ops.EagerTensor'>
   base_displacement_vertical_rotation <class 'tensorflow.python.framework.ops.EagerTensor'>
   gripper_closedness_action <class 'tensorflow.python.framework.ops.EagerTensor'>
   rotation_delta <class 'tensorflow.python.framework.ops.EagerTensor'>
   terminate_episode <class 'tensorflow.python.framework.ops.EagerTensor'>
   world_vector <class 'tensorflow.python.framework.ops.EagerTensor'>
is_first <class 'tensorflow.python.framework.ops.EagerTensor'>
is_last <class 'tensorflow.python.framework.ops.EagerTensor'>
is_terminal <class 'tensorflow.python.framework.ops.EagerTensor'>
observation <class 'dict'>
   base_pose_tool_reached <class 'tensorflow.python.framework.ops.EagerTensor'>
   gripper_closed <class 'tensorflow.python.framework.ops.EagerTensor'>
   gripper_closedness_commanded <class 'tensorfl

In [7]:
a = step['action']
a

{'base_displacement_vector': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 'base_displacement_vertical_rotation': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 'gripper_closedness_action': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 'rotation_delta': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.15770754, -0.05468028, -0.11363582], dtype=float32)>,
 'terminate_episode': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 0], dtype=int32)>,
 'world_vector': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.05849131, -0.00888083, -0.01928543], dtype=float32)>}

In [ ]:
# def view_datasets():
#     cat = catalog_names.pop(0)
#     catalog ='gs://gresearch/robotics/' + cat + '/'
#     try: builder = tfds.builder_from_directory(catalog + '0.1.0')
#     except:
#         try: builder = tfds.builder_from_directory(catalog + '0.0.1')
#         except: 
#             try: builder = tfds.builder_from_directory(catalog + '1.0.0')
#             except: return
#     try: 
#         n = builder.info.splits['train'].num_examples
#         print(n)
#     except Exception as e: print(e); return
#     for i in range(n):
#         split = 'train[{}:{}]'.format(i, i + 1)
#         ds = builder.as_dataset(split=split)
#         episode = next(iter(ds))
#         steps = list(episode['steps'])
#         try:
#             images = [cv2.resize(np.array(step['observation']['image']), (256, 256)) for step in steps]
#             print(cat)
#             mediapy.show_video(images, fps=10)
#         except: return
#         try:
#             hand_images = [cv2.resize(np.array(step['observation']['hand_image']), (128, 128)) for step in steps]
#             print(cat)
#             mediapy.show_video(hand_images, fps=10)
#         except: return
#         return
# while True:
#     view_datasets()
#     # if input('continue? (y/n) ') == 'n': break